name: Bug report
description: This issue template is designed to help you report problems and suggest improvements for our project.
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Describe the issue in detail here, including any relevant context or background information. Be clear and concise.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior (bug)
      placeholder: |
        Example:
        1. Go to Main tab
        2. Tap to the music
        3. See error
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crashlog
      description: |
        **Do not put text from crashlog, include zipped Crashlog_File.ips instead**
      value: |
        **To find and attach your crashlog:**
        1. Open the Analytics & Improvements section of Settings on the device. See Share analytics, diagnostics, and usage information with Apple.
        2. Tap Analytics Data.
        3. Locate the log for your app. The log name starts with YouTubeMusic_<DateTime>.
        4. Select the desired log.
        5. Tap the Share icon, save it in the Files app, then zip saved file.
        6. **Drag and drop your zip file below.**
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Post Requisites
      description: |
        **IMPORTANT:** Read carefully before checking the box.
      options:
        - label: I have checked that a similar issue has not been reported before.
          required: true
        - label: Verified the relevance of the project and the version you are using.
          required: true
        - label: Provided a detailed description of the problem and have filled in all required fields.
          required: true
        - label: By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
          required: true
        - label: I did not answer truthfully to **ALL** the above checkboxes.
          required: false
