name: Feature request
description: This template is designed to help you suggest improvements or new features for our project.
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Describe the feature request
      description: Describe the feature or enhancement in detail here. Include any relevant context or background information. Be clear and concise.
      placeholder: |
        Enter your description here
      render: yaml
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Post Requisites
      description: |
        **IMPORTANT:** Read carefully before checking the box.
      options:
        - label: I have checked that a similar feature request has not been reported before.
          required: true
        - label: Verified the relevance of the project and the version you are using.
          required: true
        - label: Provided a detailed description of the request and have filled in all required fields.
          required: true
        - label: I did not answer truthfully to **ALL** the above checkboxes.
          required: false
        - label: By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**
          required: true
