name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Add YTMusicUltimateDX submodules
        run: |
          git submodule add https://github.com/PoomSmart/YouTubeHeader.git Tweaks/YouTubeHeader
          git submodule add https://github.com/PoomSmart/YouTubeMusicHeader.git Tweaks/YouTubeMusicHeader
          git submodule add https://github.com/PoomSmart/YTMABConfig.git Tweaks/YTMABConfig
          git submodule add https://github.com/PoomSmart/Return-YouTube-Dislikes.git Tweaks/Return-YouTube-Dislikes
          git submodule add https://github.com/PoomSmart/Return-YouTube-Music-Dislikes.git Tweaks/Return-YouTube-Music-Dislikes
          git add .
          git commit -m "added YTMusicUltimateDX submodules"
          git push origin

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote
          git add .
          git commit -m "updated submodules"
          git push origin
        continue-on-error: true

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
